### PR TITLE
Childcare blog post

### PR DESCRIPTION
**Pull request by davidfischer**
Changes proposed in this PR:

- Add a new childcare blog with information on the childcare provider
- Add a link to the post on the venue page

I tentatively put the date on the post for a week from today but there is no real rush from a booking childcare perspective. The goal with getting the post earlier is to make sure that attendees considering buying a ticket don't hold off due to questions around childcare.

## Open Questions/Issues

- [x] Are we sticking with the "up to $100 per day" verbiage? I don't believe we held people to that last year.
- [x] `childcare-info.png` has the Djangocon 2018 logo. Shall I create a new one?
- [ ] Unlike 2018 and 2017, we didn't run a survey about what people need from childcare. Are we ok with that? Should we maybe add a phrase like "If you have additional childcare needs, don't hesitate to email..."?
- [ ] Last year there was not an explicit childcare sponsor. If that has changed, we should thank them in the post.

### CODE REVIEW

**Comment by KatherineMichel** [comment]
@davidfischer I can't answer the other questions, but in terms of the logo, you're right. We shouldn't use an old logo. It would be great if you could update it, if you don't mind. That might have been made with Buffer's Pablo. Not sure. I don't usually make those. We have some logo resources in a different repo: https://github.com/djangocon/resources/tree/master/us-2019

**Comment by davidfischer** [comment]
I updated the childcare graphic with the 2019 logo. The photo underneath is from [here](https://unsplash.com/photos/1zR3WNSTnvY) and is [licensed for re-use](https://unsplash.com/license).

**Comment by craigbruce** [comment]
@davidfischer regarding daily amount I believe we put that in so costs didn't run away (e.g. 8 hours for all tutorial/talk/sprint days could have used the entire budget). We have found the total requests for childcare to be low so have been able to accommodate higher amounts, after the event. Perhaps we could change the wording to "up to $150 per day".

**Comment by davidfischer** [comment]
I updated the date on the post and set it tentatively to next Tuesday. Are we good with this going out? It should go out soon.

I updated the $100/day -> $150/day.

**Comment by KatherineMichel** [comment]
@davidfischer I fixed one typo. Otherwise, lgtm!

**Pull request merged**
