### PR TITLE
Six Feet Up Bronze

### PR DESCRIPTION
**Pull request by daheats**
Closes # .

Changes proposed in this PR:

-
-

### CODE REVIEW

**Comment by KatherineMichel** [comment]
Some of the sponsors have more than one file now. Is that on purpose? We should probably go with one each, unless there is a specific reason for more than one.

**Comment by daheats** [comment]
Hey,

Besides Six Feet Up who has more than one? They’re both a lanyard and a bronze sponsor so I wasn’t sure how to show that except for doing the double mentions. Totally open to something else if there’s a better design idea! :)

Heather

**Comment by KatherineMichel** [comment]
@daheats Ok, that's fine. I didn't know there was a reason. I think PG Experts, Netlandish and Vinta also have two.

**Comment by daheats** [comment]
Weird - it may also be due to the fact it appears the older posts from other years have come over into this years. Probably happened when the site was copied. 

Is that what you’re seeing?

Thanks! 

Heather

**Comment by KatherineMichel** [comment]
@daheats Yeah, I suspect they were left as boilerplate for this year. I didn't realize they were there at first.

**Pull request merged**
