### PR TITLE
Theming Groundwork

### PR DESCRIPTION
**Pull request by mtrythall**
This covers the basics we need to begin theming:

* Refactors the theming variable system, using abstract names instead of theme-specific names.
* Applies these new colors in a limited way.
* Updates parts of the site to feature the new logo
* Begins some work (mostly experimentation) with typography
* Drops in the new icons for 2019

This doesn't quite start skinning the site, but the landing page ought to be fine. Subsequent PRs will see the site better reflect this new theme work.

### CODE REVIEW

**Comment by jefftriplett** [comment]
@mtrythall with GitHub Pages, you'll need to re-build the static assets and commit those. Please see my update in the `master` branch from last night which re-enables this. Otherwise, I'm not sure how to get GitHub to build these without making a few other changes.

**Comment by mtrythall** [comment]
Per Slack, thanks for the pointer. I thought this was all deploying to Netlify, which was randomly failing for other reasons.

I have merged in your `master` branch, so I believe this is good to go @jefftriplett.

**Comment by jefftriplett** [comment]
@mtrythall I checked out the preview link and that's working now. You might check it out and let me know what you need from us. I see the colors update, the dropdown menus kind of blow up, and the header images are gone. Since its shows the homepage vs. the splash page, I'm not sure if I'm seeing what you want me to or not.

**Comment by mtrythall** [comment]
@jefftriplett Yes, that's right. All this does is update the color system and fonts. Things are wonky, but the next PR will address all of that. If the splash page is still intact then I think we're good.

**Comment by mtrythall** [comment]
Merging this in with the latest work, so closing this PR.

**Pull request closed without merging**
